variables:
    PORT: 5000

stages:
    - build
    - test
    - staging
    - production

build-job:
  stage: build
  script:
    - echo "Building the web app..."
    - mvn compile

test-job:
  stage: test
  script:
    - echo "Testing the web app..."
    - mvn test

deploy-staging:
  stage: staging
  script:
    - echo "Deploying the web app into the production..."
    - mvn package
    - start-stop-daemon --stop --name simplewebapp --oknodo
    - start-stop-daemon --start --background --startas /bin/sh --name simplewebapp -- target/bin/simplewebapp

deploy-prod:
  stage: production
  script:
    - dpl --provider=heroku --app=xz1919-simplewebapp --api-key=d897167b-b3ca-41fd-a287-0b3ce5c68697
