variables:
    PORT: 5000

stages:
    - build
    - test
    - deploy

build-job:
  stage: build
  script:
    - echo "Building the web app..."
    - mvn compile

test-job:
  stage: test
  script:
    - echo "Testing the web app..."
    - mvn test

deploy-prod:
  stage: deploy
  script:
    - echo "Deploying the web app into the production..."
    - mvn package && sh target/bin/simplewebapp
    - dpl --provider=heroku --app=xz1919-simplewebapp --api-key=d897167b-b3ca-41fd-a287-0b3ce5c68697
